### ISSUE TITLE
Async functions support

### ISSUE THREAD

**Issue by tailhook** [andrewhickman/fn-error-context#1]
Hi! This is a nice crate.

But it doesn't support `async` functions. Is it hard to add support?

**Comment by andrewhickman** [comment]
Hi!

I did experiment with async function support and didnt find a super easy way to do it (compared to sync functions)

Once async closures are stable it will become easy to implement. Until then feel free to raise a PR!

**Comment by tailhook** [comment]
For anything that are not methods this approach should work: https://github.com/yoshuawuyts/context-attribute/blob/master/src/lib.rs
Async methods are harder :(
